M48
; DRILL file KiCad 10.0.3-10.0.3~ubuntu24.04.1 date 2026-05-28T09:56:04
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-28T09:56:04-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3-10.0.3~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X54.468Y-42.5
X54.468Y-72.5
X94.5Y-42.5
X94.5Y-72.5
M30
